Task_2_1_1
ViktorPetrovichBarinov/OOP pull request #11
Opened 2024-02-07 03:58 UTC by ViktorPetrovichBarinov

2024-02-14 10:10 UTC, BIGNIKi requested changes

2024-02-14 10:10 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/org/example/Logic.java
> +    static boolean sequentialCalculation(long[] number) {
Каждый подход к поиску простых чисел вынести в отдельный класс, наследующий абстрактный класс, с методом find.
Много разных решений одной и той же задачи не должны находиться в одном классе.

2024-02-14 10:10 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/org/example/Logic.java
> +    static boolean sequentialCalculation(long[] number) {
Почему у всех методов для поиска простых чисел модификатор доступа - package visible? С таким модификатором доступа никто не сможет использовать твою библиотеку в своих проектах.

2024-02-14 10:10 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/org/example/Logic.java
> +    private static AtomicBoolean threadCalculationResult = new AtomicBoolean(); //хранит результат,
Раз уж ссылки на них никто не может менять, нужно это явно указывать ключевым словом final

2024-02-14 10:10 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/org/example/Logic.java
> +            if (!isPrimeNumber(arrayIndex)) {
Ищешь везде не простые числа, хотя договорились искать простые.
Мне не принципиально, можно не переделывать.

2024-02-14 10:10 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/org/example/Logic.java
> +        for (long arrayIndex : number) {
Сделай через stream

2024-02-14 10:10 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/org/example/Logic.java
> +    static boolean threadCalculation(long[] number, int numberOfThreads) {
Метод очень перегружен, нужно декомпозировать: создание тредов, запуск, ожидание завершения.

2024-02-14 10:10 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/org/example/Logic.java
> +        Thread[] threads = new Thread[numberOfThreads]; //инициализируем
А если передали отрицательное число numberOfThreads?

2024-02-14 10:10 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/org/example/Logic.java
> +        System.setProperty("java.util.concurrent.ForkJoinPool.common.parallelism",
Нужно сбрасывать к default значению после использования, иначе пользователь твоей библиотеки может наткнуться на неочевидные проблемы.
А вообще, лучше использовать ForkJoinPool.

2024-02-14 10:10 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/org/example/Logic.java
> +            threads[i] = new Thread(() -> {
Такие большие лямбда-выражения нужно выносить в отдельные методы или вообще лучше отдельный класс, наследующий Thread сделать.

2024-02-14 10:10 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/org/example/Logic.java
> +                    int index = threadCalculationIndex.getAndIncrement();
Такая реализация существенно медленнее подхода, когда весь массив делится на равные части и обработка каждой части делегируется разным потокам, т.к. пока один из потоков пытается сделать getAndIncrement, все остальные потоки, которые пытаются сделать то же самое, ждут тот первый поток, который начал исполнять эту операцию, получается, что они могут блокировать работу друг друга.

Сделай через обработку независимых частей

2024-02-14 10:11 UTC, BIGNIKi requested changes

2024-02-14 10:11 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/org/example/Logic.java
> +package org.example;
Не увидел в репозитории полученный график

2024-02-16 08:06 UTC, ViktorPetrovichBarinov commented on Task_2_1_1/src/main/java/org/example/Logic.java
> +        System.setProperty("java.util.concurrent.ForkJoinPool.common.parallelism",
Использовать clear.property.

2024-03-01 08:59 UTC, BIGNIKi approved these changes

2024-03-05 17:04 UTC, merged