Task_2_3_1
ViktorPetrovichBarinov/OOP pull request #15
Opened 2024-04-02 18:40 UTC by ViktorPetrovichBarinov

2024-04-10 06:08 UTC, BIGNIKi requested changes

2024-04-10 06:08 UTC, BIGNIKi commented on Task_2_3_1/src/main/java/org/example/task_2_3_1/Game.java
> +        new AnimationTimer() {
Сделать через Thread (свой)

2024-04-10 06:08 UTC, BIGNIKi commented on Task_2_3_1/src/main/java/org/example/task_2_3_1/Field.java
> +    public void generateFood() {
Проверять, что есть возможность поставить еду на поле (через stream)

2024-04-10 06:08 UTC, BIGNIKi commented on Task_2_3_1/src/main/java/org/example/task_2_3_1/Field.java
> +    public void generateFood() {
TODO: для себя, найти баг

2024-04-16 15:34 UTC, ViktorPetrovichBarinov commented on Task_2_3_1/src/main/java/org/example/task_2_3_1/Field.java
> +    public void generateFood() {
Нету там ничего

2024-04-16 16:16 UTC, ViktorPetrovichBarinov commented on Task_2_3_1/src/main/java/org/example/task_2_3_1/Game.java
> +        new AnimationTimer() {
реализовал

2024-04-16 16:42 UTC, ViktorPetrovichBarinov commented on Task_2_3_1/src/main/java/org/example/task_2_3_1/Field.java
> +    public void generateFood() {
Реализовал

2024-05-03 18:07 UTC, merged