Task_1_1_2
ViktorPetrovichBarinov/OOP pull request #3
Opened 2023-09-28 20:50 UTC by ViktorPetrovichBarinov

2023-10-01 07:36 UTC, BIGNIKi requested changes

2023-10-01 07:36 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/ru/nsu/chudinov/Main.java
> +    public static void main(String[] args) {
В Main добавь пример из задачи.
Polynomial p1 = new Polynomial(new int[] {4, 3, 6, 7});
Polynomial p2 = new Polynomial(new int[] {3, 2, 8});
System.out.println(p1.plus(p2.differentiate(1)).toString());
System.out.println(p1.times(p2).evaluate(2));

2023-10-01 07:36 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/ru/nsu/chudinov/Polynomial.java
> +            throw new IllegalArgumentException("Array must be non empty!");
Почему решил запретить создавать пустой полином? Пустой полином тоже имеет математический смысл. Он равен нулю и с ним тоже можно производить математические операции.

2023-10-01 07:36 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/ru/nsu/chudinov/Polynomial.java
> +            result.append("empty polynomial");
Да я думаю лучше 0 выводить. Пустой полином - это ноль

2023-10-01 07:36 UTC, BIGNIKi commented on Task_1_1_2/src/run.bat
> +javac -d .\out .\main\java\ru\nsu\chudinov\*.java
Скрипты для компиляции, генерации документации и прочее в этой и следующих задачах не обязательны.

2023-10-01 07:36 UTC, BIGNIKi commented on Task_1_1_2/src/test/java/ru/nsu/chudinov/PolynomialTest.java
> +    private static Stream<Arguments> constructorPolynomialTest() {
Лучше методы с генерацией данных для теста писать под самим тестом, который использует эти данные.

2023-10-01 07:36 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/ru/nsu/chudinov/Polynomial.java
> +    public boolean compare(Polynomial other) {
Чтобы привыкать к интерфейсам, реализуй интерфейс Comparable.

2023-10-01 07:36 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/ru/nsu/chudinov/Polynomial.java
> +    public boolean compare(Polynomial other) {
Также по заданию нужно реализовать сравнение на равенство с другим многочленом.
Для этого переопредели метод Equals из класса Object

2023-10-01 07:52 UTC, BIGNIKi commented
Очень круто, что применил Generic`и👍

2023-10-01 08:09 UTC, ViktorPetrovichBarinov commented on Task_1_1_2/src/main/java/ru/nsu/chudinov/Polynomial.java
> +            throw new IllegalArgumentException("Array must be non empty!");
Ну у меня была логика, что пустой массив это ничего и соответственно не полином вообще. А полиному который равен нулю соответствует массив {0} и вот с ним можно проводить математические операции. Так же можно составить массив {0, 0, 0, 0}  и вообще из любого количества нулей.

2023-10-01 08:11 UTC, ViktorPetrovichBarinov commented on Task_1_1_2/src/test/java/ru/nsu/chudinov/PolynomialTest.java
> +    private static Stream<Arguments> constructorPolynomialTest() {
style check ругается на это, говорит прямо противоположное

2023-10-20 09:34 UTC, BIGNIKi approved these changes

2023-10-25 17:53 UTC, merged