Task_1_2_1
ViktorPetrovichBarinov/OOP pull request #4
Opened 2023-10-18 14:12 UTC by ViktorPetrovichBarinov

2023-10-20 09:40 UTC, BIGNIKi requested changes

2023-10-20 09:40 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +    public static void main(String[] args) {
Вынести в Main

2023-10-20 09:40 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +public class Tree<T> implements Iterable<T> {
Реализовать интерфейс Cloneable. https://www.techiedelight.com/ru/construct-deep-copy-list-java/

2023-10-20 09:40 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +    public Tree<T> addChild(Tree<T> subTree) {
Сделай своё исключение и кидай, если передали null

2023-10-20 09:40 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +    public Tree<T> addChild(Tree<T> subTree) {
Делать копию входного subTree и прицеплять именно его. Входной не менять

2023-10-20 09:40 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +    public Tree<T> addChild(T root) {
null обработать

2023-10-20 09:40 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +    public void printTree() {
Сделать toSTring

2023-10-20 09:40 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +        public TreeIterator() {
Вынести в отдельный класс

2023-10-20 09:40 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +        public T next() {
Если след элемента нет, нужно кидать NoSuchElementException
Про паттерн итератор читать тут
https://javarush.com/groups/posts/1884-pattern-iterator

2023-10-20 09:40 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +            if (expectedModCount != modCount) {
А если наше дерево будет очень долгоживущим, modCount переполнится и снова станет равным expectedModCount.
Переделывать не обязательно, но порассуждать об этом можно: какие есть варианты избежать такую проблему?

2023-10-25 13:45 UTC, ViktorPetrovichBarinov commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +    public static void main(String[] args) {
+

2023-10-25 13:55 UTC, ViktorPetrovichBarinov commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +    public void printTree() {
+

2023-10-25 15:57 UTC, ViktorPetrovichBarinov commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +public class Tree<T> implements Iterable<T> {
+

2023-10-25 16:05 UTC, ViktorPetrovichBarinov commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +    public Tree<T> addChild(Tree<T> subTree) {
+

2023-10-25 16:05 UTC, ViktorPetrovichBarinov commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +    public Tree<T> addChild(Tree<T> subTree) {
+

2023-10-25 16:08 UTC, ViktorPetrovichBarinov commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +    public Tree<T> addChild(T root) {
+

2023-10-25 16:22 UTC, ViktorPetrovichBarinov commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +        public TreeIterator() {
+

2023-10-25 16:24 UTC, ViktorPetrovichBarinov commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +        public T next() {
+

2023-10-25 16:36 UTC, ViktorPetrovichBarinov commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +            if (expectedModCount != modCount) {
+

2023-10-26 07:52 UTC, BIGNIKi approved these changes
Принял

2023-10-26 07:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/chudinov/Tree.java
> +    public Tree<T> addChild(T root) throws NullReferenceError {
Если null? Кидать exception

2023-10-26 08:04 UTC, merged