Task_1_2_2
ViktorPetrovichBarinov/OOP pull request #5
Opened 2023-11-01 19:27 UTC by ViktorPetrovichBarinov

2023-11-02 09:00 UTC, BIGNIKi requested changes
Защитил

2023-11-02 09:00 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/ru/nsu/chudinov/Graph.java
> +    protected static class ConnectedVertex<T> implements Comparable<ConnectedVertex> {
Вынести в другой класс

2023-11-02 09:00 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/ru/nsu/chudinov/Graph.java
> +    public abstract Boolean addVertex (Vertex<T> vertex);
Все методы возвращать void + кидать исключения

2023-11-02 09:00 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/ru/nsu/chudinov/IncidenceMatrix.java
> +            this.flag = flag;
flag через enum сделать

2023-11-02 09:00 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/ru/nsu/chudinov/IncidenceMatrix.java
> +public class IncidenceMatrix<T> extends Graph<T> {
Тесты написать

2023-11-08 14:35 UTC, ViktorPetrovichBarinov commented on Task_1_2_2/src/main/java/ru/nsu/chudinov/Graph.java
> +    protected static class ConnectedVertex<T> implements Comparable<ConnectedVertex> {
+

2023-11-08 14:49 UTC, ViktorPetrovichBarinov commented on Task_1_2_2/src/main/java/ru/nsu/chudinov/Graph.java
> +    public abstract Boolean addVertex (Vertex<T> vertex);
+

2023-11-08 15:21 UTC, ViktorPetrovichBarinov commented on Task_1_2_2/src/main/java/ru/nsu/chudinov/IncidenceMatrix.java
> +            this.flag = flag;
+

2023-11-19 07:47 UTC, BIGNIKi requested changes

2023-11-19 07:47 UTC, BIGNIKi commented on Task_1_2_2/src/test/java/ru/nsu/chudinov/MainTest.java
> +            FileReader reader = new FileReader(file);
Не закрываешь ресурсы, которые надо закрывать. Используй try with resources

2023-11-19 07:47 UTC, BIGNIKi commented on Task_1_2_2/src/test/java/ru/nsu/chudinov/MainTest.java
> +        try {
Один и тот же код для чтения с файла переиспользуешь несколько раз, что не есть хорошо.
Надо добавить в Graph метод для чтения графа из файла.

2023-11-19 07:47 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/ru/nsu/chudinov/Graph.java
> +    public ArrayList<Edge<T>> getEdge(Vertex<T> vertex) {
А вершину как получить?

2023-11-22 13:23 UTC, ViktorPetrovichBarinov commented on Task_1_2_2/src/test/java/ru/nsu/chudinov/MainTest.java
> +            FileReader reader = new FileReader(file);
+

2023-11-22 13:45 UTC, ViktorPetrovichBarinov commented on Task_1_2_2/src/test/java/ru/nsu/chudinov/MainTest.java
> +        try {
+

2023-11-22 13:53 UTC, ViktorPetrovichBarinov commented on Task_1_2_2/src/main/java/ru/nsu/chudinov/Graph.java
> +    public ArrayList<Edge<T>> getEdge(Vertex<T> vertex) {
Вершину не требуется получить ни по задаче, ни по структуре. Данный метод использовался в реализации алгоритма поиска кротчайшего пути и по сути своей является вспомогательным. Единственное, что метод должен быть приватным.

2023-11-22 13:57 UTC, ViktorPetrovichBarinov commented on Task_1_2_2/src/main/java/ru/nsu/chudinov/Graph.java
> +    public ArrayList<Edge<T>> getEdge(Vertex<T> vertex) {
+ метод возвращает список рёбер инцидентных с вершиной. А не одно какое-то ребро. Поменял название на более читаемое.

2023-11-23 08:47 UTC, BIGNIKi approved these changes

2023-11-23 17:42 UTC, merged