Task_1_3_1
ViktorPetrovichBarinov/OOP pull request #7
Opened 2023-11-15 17:40 UTC by ViktorPetrovichBarinov

2023-11-16 08:44 UTC, BIGNIKi requested changes
Защитил

2023-11-16 08:44 UTC, BIGNIKi commented on Task_1_3_1/src/main/java/org/example/KMP.java
> +            BufferedReader br = new BufferedReader(
Try with resources используй

2023-11-16 08:44 UTC, BIGNIKi commented on Task_1_3_1/src/main/java/org/example/KMP.java
> +                    new InputStreamReader(
Давай еще сделаешь чтение файла из ресурсов. Полезно будет разобраться, что такое ресурсы в джаве, где ждет их gradle и что gradle с ними делает при сборке.

2023-11-16 08:44 UTC, BIGNIKi commented on Task_1_3_1/src/test/java/org/example/KMPTest.java
> +public class KMPTest {
Сделай еще тестовый метод, который генерит большой файл (15-20 гигов), ищет в нем подстроку (какую-нибудь небольшую, которая находится в самом конце файла). Также программно удалить этот файл. (как junit тест его не делай, кто знает как на это github workflow отреагирует)

2023-11-22 14:43 UTC, ViktorPetrovichBarinov commented on Task_1_3_1/src/main/java/org/example/KMP.java
> +            BufferedReader br = new BufferedReader(
+

2023-11-22 14:43 UTC, ViktorPetrovichBarinov commented on Task_1_3_1/src/main/java/org/example/KMP.java
> +                    new InputStreamReader(
+

2023-11-22 15:25 UTC, ViktorPetrovichBarinov commented on Task_1_3_1/src/test/java/org/example/KMPTest.java
> +public class KMPTest {
+

2023-11-23 08:57 UTC, BIGNIKi approved these changes

2023-11-23 17:42 UTC, merged